source 'http://rubygems.org'

gem 'slack-ruby-bot'
gem 'dotenv'
gem 'wolfram', '~> 0.2.1'
gem 'http'
# gem 'mechanize'
gem 'screencap'
gem 'imgur2'
gem 'async-websocket', '~> 0.8.0'
gem 'rack'
gem 'rss'