source 'http://rubygems.org'

gem 'async-websocket', '~> 0.8.0'
gem 'bundler'
gem 'dotenv'
gem 'http'
gem 'imgur2'
gem 'rack'
gem 'rspec'
gem 'rss'
gem 'screencap'
gem 'slack-ruby-bot'
gem 'wolfram', '~> 0.2.1'
